on:
  push:
    paths: 
      - ".github/workflows/android-emulator.yaml"

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    name: android emulator
    steps:
      - uses: actions/checkout@v1
#       - run: ./adb_devices.sh
      - uses: malinskiy/action-android/install-sdk@release/0.0.5
      - run: |
          yes | sdkmanager "system-images;android-29;google_apis;x86_64" 
          
          
          
#       - run: ./adb_devices.sh
#       - run: adb devices
#       - run: echo $ANDROID_HOME
#       - run: ./start_emulator.sh


