on:
  push:
    paths: 
      - ".github/workflows/android-emulator.yaml"

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    name: android emulator
    steps:
      - run: ls "$ANDROID_HOME/build-tools"
      - run: env
