on:
  push:
    paths: 
      - ".github/workflows/android-emulator.yaml"

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    name: android emulator
    steps:
      - run: pwd
      - run: ls -la
      - run: ./start_emulator.sh
