on:
  push:
    paths: 
      - ".github/workflows/android-emulator.yaml"

env:
  ANDROID_BUILD_TOOLS: "$ANDROID_HOME/build-tools/29.0.2"

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    name: android emulator
    steps:
      - run: start_emulator.sh
