name: Upload to release
on:
  push:
    tags:
      - 'upload*'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: "make files"
      run: |
        echo "hi" > test.txt
        echo "ho2" > test2.txt
    - uses: avdim/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "test.txt; test2*"
        tags: true
        draft: false
        prerelease: false
        overwrite: true
        verbose: true
