name: Pull Request

on:
  pull_request:
    branches:
      - master
    
      
jobs:
  Some-job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}
      - name: unit tests
        run: echo "hi"
