name: secret
on:
  push:
    tags:
      - "secret*"
jobs:
  label:
    strategy:
      matrix:
        os: [ubuntu-18.04] #, macos-latest, windows-latest
        java_version: [1.8] #, 10, 11, 12
    runs-on: ${{ matrix.os }}
    steps:
      - name: secret info
        run: |
          echo "${{ secrets.secret1 }}"
      - name: file from secret
        uses: finnp/create-file-action@1.0.0
        env: 
          FILE_NAME: "secret.txt"
          FILE_DATE: "${{ secrets.secret1 }}"
      - name: "list files"
        run: |
          ls -la
          cat secret.txt
          du -sh *
          
